import express from "express";
import { AdminRoutes } from "./admin.route.js";
import { CategoryRoutes } from "./category.route.js";
import { UserRoutes } from "./user.route.js";
import { JobRoute } from "./job.route.js";
import { FreelancerRoutes } from "./freelancer.route.js";
import { FreelancerServicesRoutes } from "./freelancerServices.route.js";
import { ServiceApplicationsRoutes } from "./serviceApplications.route.js";
import { WalletRoutes } from "./wallet.route.js";
import { WithdrawalRoutes } from "./withdrawal.route.js";
import { BannerRoutes } from "./banner.route.js";
const router = express.Router();
router.use("/admin", AdminRoutes);
router.use("/category", CategoryRoutes);
router.use("/user", UserRoutes);
router.use("/job", JobRoute);
router.use("/freelancer", FreelancerRoutes);
router.use("/freelancer-services", FreelancerServicesRoutes);
router.use("/service-booking", ServiceApplicationsRoutes);
router.use("/wallet", WalletRoutes);
router.use("/withdrawal", WithdrawalRoutes);
router.use("/banner", BannerRoutes);
export default router;
